import { LanguageOption } from "./types";

export const CONTACT_INFO = {
  brand: "Enuncia Global",
  phone: "+91-93150 56112",
  email: "info@enuncia.global",
  website: "www.enuncia.global"
};

export const LANGUAGES: LanguageOption[] = [
  // Major Global & European
  { name: "English", script: "Latin", region: "Global", colors: ["Navy Blue", "White", "Red"] },
  { name: "Spanish", script: "Latin", region: "Spain/Latin America", colors: ["Red", "Yellow", "Orange"] },
  { name: "Mandarin Chinese", script: "Chinese Characters", region: "China", colors: ["Red", "Gold", "Jade"] },
  { name: "French", script: "Latin", region: "France", colors: ["Blue", "White", "Red"] },
  { name: "German", script: "Latin", region: "Germany", colors: ["Black", "Red", "Gold"] },
  { name: "Russian", script: "Cyrillic", region: "Russia", colors: ["White", "Blue", "Red"] },
  { name: "Portuguese", script: "Latin", region: "Portugal/Brazil", colors: ["Green", "Yellow", "Blue"] },
  { name: "Italian", script: "Latin", region: "Italy", colors: ["Green", "White", "Red"] },
  { name: "Dutch", script: "Latin", region: "Netherlands", colors: ["Orange", "Blue", "White"] },
  { name: "Polish", script: "Latin", region: "Poland", colors: ["White", "Red"] },
  { name: "Ukrainian", script: "Cyrillic", region: "Ukraine", colors: ["Blue", "Yellow"] },
  { name: "Romanian", script: "Latin", region: "Romania", colors: ["Blue", "Yellow", "Red"] },
  { name: "Greek", script: "Greek", region: "Greece", colors: ["Blue", "White"] },
  { name: "Hungarian", script: "Latin", region: "Hungary", colors: ["Red", "White", "Green"] },
  { name: "Czech", script: "Latin", region: "Czech Republic", colors: ["White", "Red", "Blue"] },
  { name: "Swedish", script: "Latin", region: "Sweden", colors: ["Blue", "Yellow"] },
  { name: "Danish", script: "Latin", region: "Denmark", colors: ["Red", "White"] },
  { name: "Finnish", script: "Latin", region: "Finland", colors: ["White", "Blue"] },
  { name: "Norwegian", script: "Latin", region: "Norway", colors: ["Red", "White", "Blue"] },
  { name: "Slovak", script: "Latin", region: "Slovakia", colors: ["White", "Blue", "Red"] },
  { name: "Bulgarian", script: "Cyrillic", region: "Bulgaria", colors: ["White", "Green", "Red"] },
  { name: "Serbo-Croatian", script: "Latin/Cyrillic", region: "Balkans", colors: ["Blue", "White", "Red"] },
  { name: "Lithuanian", script: "Latin", region: "Lithuania", colors: ["Yellow", "Green", "Red"] },
  { name: "Catalan", script: "Latin", region: "Spain", colors: ["Yellow", "Red"] },
  { name: "Belarusian", script: "Cyrillic", region: "Belarus", colors: ["Red", "Green", "White"] },

  // Asian & Pacific
  { name: "Hindi", script: "Devanagari", region: "India", colors: ["Saffron", "White", "Green"] },
  { name: "Bengali", script: "Bengali", region: "India/Bangladesh", colors: ["Green", "Red"] },
  { name: "Japanese", script: "Kanji/Kana", region: "Japan", colors: ["White", "Red", "Pink"] },
  { name: "Punjabi", script: "Gurmukhi", region: "India/Pakistan", colors: ["Orange", "Blue", "White"] },
  { name: "Javanese", script: "Latin", region: "Indonesia", colors: ["Red", "White"] },
  { name: "Malay/Indonesian", script: "Latin", region: "Southeast Asia", colors: ["Red", "White", "Yellow"] },
  { name: "Telugu", script: "Telugu", region: "India", colors: ["White", "Green", "Saffron"] },
  { name: "Vietnamese", script: "Latin", region: "Vietnam", colors: ["Red", "Yellow"] },
  { name: "Korean", script: "Hangul", region: "Korea", colors: ["Red", "Blue", "Black", "White"] },
  { name: "Marathi", script: "Devanagari", region: "India", colors: ["Orange", "White", "Green"] },
  { name: "Tamil", script: "Tamil", region: "India/Sri Lanka", colors: ["Red", "White", "Black"] },
  { name: "Urdu", script: "Arabic", region: "Pakistan/India", colors: ["Green", "White"] },
  { name: "Yue Chinese (Cantonese)", script: "Chinese Characters", region: "Hong Kong", colors: ["Red", "White", "Pink"] },
  { name: "Thai", script: "Thai", region: "Thailand", colors: ["Red", "White", "Blue"] },
  { name: "Gujarati", script: "Gujarati", region: "India", colors: ["Orange", "Red", "Yellow"] },
  { name: "Kannada", script: "Kannada", region: "India", colors: ["Yellow", "Red"] },
  { name: "Malayalam", script: "Malayalam", region: "India", colors: ["Green", "Red", "White"] },
  { name: "Sundanese", script: "Latin", region: "Indonesia", colors: ["Green", "Yellow", "Blue"] },
  { name: "Odia", script: "Odia", region: "India", colors: ["Red", "Yellow", "White"] },
  { name: "Burmese", script: "Burmese", region: "Myanmar", colors: ["Yellow", "Green", "Red"] },
  { name: "Bhojpuri", script: "Devanagari", region: "India", colors: ["Saffron", "White"] },
  { name: "Tagalog (Filipino)", script: "Latin", region: "Philippines", colors: ["Blue", "Red", "White", "Yellow"] },
  { name: "Maithili", script: "Devanagari", region: "India/Nepal", colors: ["Red", "Yellow"] },
  { name: "Sindhi", script: "Arabic", region: "Pakistan/India", colors: ["Green", "White"] },
  { name: "Awadhi", script: "Devanagari", region: "India", colors: ["Saffron", "Green"] },
  { name: "Saraiki", script: "Arabic", region: "Pakistan", colors: ["Green", "Blue"] },
  { name: "Nepali", script: "Devanagari", region: "Nepal", colors: ["Red", "Blue", "White"] },
  { name: "Sinhalese", script: "Sinhala", region: "Sri Lanka", colors: ["Yellow", "Maroon", "Orange", "Green"] },
  { name: "Chittagonian", script: "Bengali", region: "Bangladesh", colors: ["Green", "Red"] },
  { name: "Zhuang", script: "Latin", region: "China", colors: ["Red", "Yellow"] },
  { name: "Khmer", script: "Khmer", region: "Cambodia", colors: ["Blue", "Red", "White"] },
  { name: "Assamese", script: "Bengali", region: "India", colors: ["Red", "White"] },
  { name: "Madurese", script: "Latin", region: "Indonesia", colors: ["Red", "White"] },
  { name: "Marwari", script: "Devanagari", region: "India", colors: ["Pink", "Saffron"] },
  { name: "Magahi", script: "Devanagari", region: "India", colors: ["Red", "Yellow"] },
  { name: "Haryanvi", script: "Devanagari", region: "India", colors: ["Green", "White"] },
  { name: "Chhattisgarhi", script: "Devanagari", region: "India", colors: ["Green", "Orange"] },
  { name: "Deccan", script: "Devanagari", region: "India", colors: ["Saffron", "Green"] },
  { name: "Sylheti", script: "Sylheti", region: "Bangladesh/India", colors: ["Green", "Red"] },
  { name: "Dhundhari", script: "Devanagari", region: "India", colors: ["Orange", "Green"] },
  { name: "Eastern Min", script: "Chinese Characters", region: "China", colors: ["Red", "Gold"] },
  { name: "Ilocano", script: "Latin", region: "Philippines", colors: ["Blue", "Yellow", "Red"] },
  { name: "Hmong", script: "Pahawh", region: "Southeast Asia", colors: ["Red", "Green", "Black"] },
  { name: "Uyghur", script: "Arabic", region: "China", colors: ["Blue", "White"] },
  { name: "Hiligaynon", script: "Latin", region: "Philippines", colors: ["Blue", "Yellow"] },
  { name: "Balochi", script: "Arabic", region: "Pakistan", colors: ["Green", "Red", "Blue"] },
  { name: "Konkani", script: "Devanagari", region: "India", colors: ["Red", "White", "Green"] },
  { name: "Tajik", script: "Cyrillic", region: "Tajikistan", colors: ["Red", "White", "Green"] },
  { name: "Tibetan", script: "Tibetan", region: "Tibet", colors: ["Blue", "Yellow", "Red", "White"] },

  // Middle East & Central Asia
  { name: "Arabic", script: "Arabic", region: "Middle East", colors: ["Green", "Black", "Gold"] },
  { name: "Turkish", script: "Latin", region: "Turkey", colors: ["Red", "White"] },
  { name: "Persian (Farsi)", script: "Arabic", region: "Iran", colors: ["Green", "White", "Red"] },
  { name: "Pashto", script: "Arabic", region: "Afghanistan/Pakistan", colors: ["Black", "Red", "Green"] },
  { name: "Uzbek", script: "Latin", region: "Uzbekistan", colors: ["Blue", "White", "Green"] },
  { name: "Azerbaijani", script: "Latin", region: "Azerbaijan", colors: ["Blue", "Red", "Green"] },
  { name: "Kurdish", script: "Latin", region: "Middle East", colors: ["Red", "White", "Green", "Yellow"] },
  { name: "Turkmen", script: "Latin", region: "Turkmenistan", colors: ["Green", "White", "Red"] },
  { name: "Kazakh", script: "Cyrillic", region: "Kazakhstan", colors: ["Blue", "Gold"] },
  { name: "Hebrew", script: "Hebrew", region: "Israel", colors: ["Blue", "White"] },
  { name: "Georgian", script: "Georgian", region: "Georgia", colors: ["White", "Red"] },
  { name: "Armenian", script: "Armenian", region: "Armenia", colors: ["Red", "Blue", "Orange"] },

  // Africa
  { name: "Hausa", script: "Latin", region: "West Africa", colors: ["Green", "White"] },
  { name: "Yoruba", script: "Latin", region: "Nigeria", colors: ["Green", "White"] },
  { name: "Amharic", script: "Ge'ez", region: "Ethiopia", colors: ["Green", "Yellow", "Red"] },
  { name: "Fula", script: "Latin", region: "West Africa", colors: ["Red", "Green"] },
  { name: "Oromo", script: "Latin", region: "Ethiopia", colors: ["Red", "Green", "Yellow"] },
  { name: "Igbo", script: "Latin", region: "Nigeria", colors: ["Red", "Black", "Green"] },
  { name: "Malagasy", script: "Latin", region: "Madagascar", colors: ["White", "Red", "Green"] },
  { name: "Somali", script: "Latin", region: "Somalia", colors: ["Blue", "White"] },
  { name: "Akan", script: "Latin", region: "Ghana", colors: ["Red", "Yellow", "Green"] },
  { name: "Zulu", script: "Latin", region: "South Africa", colors: ["Red", "Green", "Yellow", "Black"] },
  { name: "Kinyarwanda", script: "Latin", region: "Rwanda", colors: ["Blue", "Yellow", "Green"] },
  { name: "Kirundi", script: "Latin", region: "Burundi", colors: ["Red", "White", "Green"] },
  { name: "Shona", script: "Latin", region: "Zimbabwe", colors: ["Green", "Yellow", "Red", "Black"] },
  { name: "Mossi", script: "Latin", region: "Burkina Faso", colors: ["Red", "Green"] },
  { name: "Xhosa", script: "Latin", region: "South Africa", colors: ["Black", "Green", "Yellow"] },
  { name: "Afrikaans", script: "Latin", region: "South Africa", colors: ["Orange", "White", "Blue"] },
  { name: "Swahili", script: "Latin", region: "East Africa", colors: ["Green", "Yellow", "Black", "Blue"] },

  // Americas
  { name: "Haitian Creole", script: "Latin", region: "Haiti", colors: ["Blue", "Red"] },
  { name: "Quechua", script: "Latin", region: "Andes", colors: ["Red", "Yellow", "Green"] },
  { name: "Guarani", script: "Latin", region: "South America", colors: ["Red", "White", "Blue"] }
];

export const ART_STYLES = [
  "Minimalist Modern",
  "3D Render with Glassmorphism",
  "Flat Illustration",
  "Neon Cyberpunk",
  "Abstract Geometric",
  "Watercolor and Ink",
  "Corporate Memphis",
  "Bauhaus Design",
  "Art Deco Luxury",
  "Paper Cutout Craft",
  "Futuristic Tech",
  "Retro Pop Art",
  "Swiss Typographic",
  "Origami Inspired",
  "Fluid Gradient"
];

export const MODEL_NAME = 'gemini-2.5-flash-image';